### PR TITLE
fix repay failing at starting MetaMask

### PR DESCRIPTION
**Pull request by patcito**
use repay instead of burn, this fixes the gasLimit issue

### CODE REVIEW

**Review by n4n0GH — CHANGES_REQUESTED** [review]
this ain't it.
repaying outstanding debt with the debt token is supposed to call `burn` and not `repay`. implementing this pr subverts expected behavior.

**Comment by patcito** [comment]
> this ain't it. repaying outstanding debt with the debt token is supposed to call `burn` and not `repay`. implementing this pr subverts expected behavior.

in the UI I can pick WETH or alETH to repay, `burn()` doesn't take a token address as params, not sure how would this work with burn() instead of repay, let me know what I'm missing and I'll try to update the PR.

edit: nvm I think I got it let me give it a try

**Comment by patcito** [comment]
ok so it seems like the error is that debtToken is alETH as returned by the contract here

https://etherscan.io/readContract?m=light&a=0x062Bf725dC4cDF947aa79Ca2aaCCD4F385b13b5c&n=mainnet&v=0x938dba3b746b3cc6d47c703aac3a7485287c0ed7#readCollapse11

However, when I try to repay in WETH, it thinks I'm using the debtToken (alETH) at this line https://github.com/alchemix-finance/alchemix-v2-frontend/blob/prod/src/components/composed/Modals/vaults/Repay.svelte#L115

**Comment by patcito** [comment]
Seems to happen when I have 0 alETH but some WETH.

**Comment by patcito** [comment]
yes, this line causes the bug, it just arbitrarly select the first token return as debtToken, in this case `tokensForVaultType[0]` returns WETH when alETH balance equals 0

https://github.com/alchemix-finance/alchemix-v2-frontend/blob/prod/src/components/composed/Modals/vaults/Repay.svelte#L209

**Comment by patcito** [comment]
@n4n0GH pushed a fix, let me know if it works for you.

**Review by n4n0GH — CHANGES_REQUESTED** [review]
the change, again, changes expected behaviour. we try to omit tokens from the selection list if the balance is 0. that way we prevent cluttering of the list with tokens the user might not have. the ux behind this is basically to only show the user the tokens they _have_ so they don't have to click through all the tokens to find the ones they can use to repay their debt with.

please provide a written thought process as to how this PR fixes the issue you're experiencing because it looks like it is just putting a bandaid on the symptoms, without actually curing the actual cause.

edit: sorry, didn't see your previous comments. so the issue seems to be a mismatch between two provided variables. but again, we don't want to clutter the list of selectable tokens with zero-balance-items. you seem to be on the right track tho.

**Comment by patcito** [comment]
> edit: sorry, didn't see your previous comments. so the issue seems to be a mismatch between two provided variables. but again, we don't want to clutter the list of selectable tokens with zero-balance-items. you seem to be on the right track tho.

Hey @n4n0GH, the UI is not being cluttered, no worries. Because there is another check to filter tokens with balance eq 0 here https://github.com/patcito/alchemix-v2-frontend/blob/fix-repay/src/components/composed/Modals/vaults/Repay.svelte#L153

So with my fix it will still only show WETH and not alETH if alETH balance is 0 but I'm still able to get the correct debtToken because `tokensForVaultType` still contains alETH but `tokensForVaultType` used for the UI doesn't so UI is not clutered :)

image

**Comment by n4n0GH** [comment]
Understood; however it's still a bandaid solution. The actual cause of the bug is here: https://github.com/alchemix-finance/alchemix-v2-frontend/blob/prod/src/components/composed/Modals/vaults/Repay.svelte#L209

Instead of `tokensForVault[0]` it should use `fullTokenList[0]` to accurately grab the debt token of the currently selected alchemist. Nothing else needs changing. If you want to change your PR I'd gladly merge it.

Cause of this bug is a wrong list of tokens being used to fetch the "debtToken" symbol.

**Comment by patcito** [comment]
> Instead of `tokensForVault[0]` it should use `fullTokenList[0]` to accurately grab the debt token of the currently selected alchemist. Nothing else needs changing. If you want to change your PR I'd gladly merge it.
> 

ok pushed

**Review by n4n0GH — APPROVED** [review]

**Pull request merged**
